name: Python Script

on:
  push:
    branches:
      - main  # Change this to match your branch name

jobs:
  build:

    runs-on: ubuntu-latest  # You can change the OS if needed

    steps:
    - uses: actions/checkout@v2  # This checks out your repository's code

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version you want to use

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Install dependencies if any

    - name: Run Python script
      run: python ../scripts/low-code.py  # Replace "your_script.py" with your script's name and update the path if needed
