name: 'Build image 1'
runs: 
  using: 'composite'  
  # if: ${{ github.ref=='refs/heads/master'}}
  steps:
  - name: Build Image      
    uses: actions/checkout@v2

  - name: get job url
    uses: Tiryoh/gha-jobid-action@v0
    id: jobs
    with:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      job_name: Build Image
