name: CI

on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Make a choice
        options:
        - staging
        - prod
jobs:
  ecr-upload:
    name: WF dispatch example
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Trigger a repo dispatch 
        id: deploy-build        
        run: |
          echo all good
