---
name: Sentry io creation
on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to run'
        required: true
        type: string
      sentry-auth-token:
        description: 'Sentry auth token'
        required: true
        type: string
      sentry-org:
        description: 'Sentry organization'
        required: true
        type: string
      sentry-project:
        description: 'Sentry project'
        required: true
        type: string
      tag-name:
        description: 'Tag name'
        required: true
        type: string
jobs:
  create-sentry:
    name: Create Sentry
    runs-on: ubuntu-latest
    steps:
      - name: Create a Sentry.io release
        if: ${{ inputs.sentry-auth-token != '' }}
        uses: tclindner/sentry-releases-action@v1.0.0
        env:
          SENTRY_AUTH_TOKEN: ${{ inputs.sentry-auth-token }}
          SENTRY_ORG: ${{ inputs.sentry-org }}
          SENTRY_PROJECT: ${{ inputs.repo-name }}
        with:
          tagName: ${{ inputs.sha }}
          environment: ${{ inputs.environment }}
