name: Deploy to dev using serverless
on:
  workflow_call:
    inputs:
      repository_full_name:
        description: 'Repository full name'
        required: true     
        type: string
      client_payload_ref:
        description: 'Client payload reference'
        required: true
        type: string 
      environment:
        description: 'Environment to run'
        required: true
        type: string

jobs:
  deploy-to-dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    steps:          
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.client_payload_ref }}

      - name: Set up node.js version
        uses: actions/setup-node@master
        with:
          node-version: 18.x
      - run: npm install -g yarn serverless
      - run: yarn install

      - name: Serverless Authentication
        run: sls config credentials --provider aws --key ${{secrets.AWS_ACCESS_KEY_ID}} --secret ${{secrets.AWS_SECRET_ACCESS_KEY}}

      - name: Deploy to dev
        run: echo "success" 
        # serverless deploy --stage dev
