name: Deploy to dev using serverless
on:
  workflow_call:
    inputs:
      repository_full_name:
        description: "Personal access token from secrets"
        required: true
        type: string
      client_payload_ref:
        description: 'Client payload reference'
        required: true
        type: string
      environment:
        description: 'Environment to be deployed to'
        required: true
        type: string    

  repository_dispatch:
    types: [deploy-dev]

jobs:
  notify-slack-build:
    uses: ./.github/workflows/notify_slack.yml
    with:
      repository_full_name: ${{ inputs.repository_full_name }}
      client_payload_ref: ${{ inputs.client_payload_ref }}
      environment: 'dev'
    secrets: inherit

  deploy-to-dev:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          ref: $CLIENT_PAYLOAD_REF

      - name: Set up node.js version
        uses: actions/setup-node@master
        with:
          node-version: 18.x
      - run: npm install -g yarn serverless
      - run: yarn install

      - name: Serverless Authentication
        run: sls config credentials --provider aws --key ${{secrets.AWS_ACCESS_KEY_ID}} --secret ${{secrets.AWS_SECRET_ACCESS_KEY}}

      - name: Deploy to dev
        run: serverless deploy --stage dev

  notify-slack-status-success:
    name: Notify Slack status for successful deployment
    needs: deploy-to-dev
    if: ${{ success() && needs.deploy-to-dev.result == 'success' }}
    uses: ./.github/workflows/notify_slack.yml
    with:
      repository_full_name: ${{ inputs.repository_full_name }}
      client_payload_ref: ${{ inputs.client_payload_ref }}
      build_status_message: 'PR Build Complete'
    secrets: inherit
  
  notify-slack-status-failure:
    name: Notify Slack status for failed deployment
    needs: deploy-to-dev
    if: ${{ failure() || needs.deploy-to-dev.result != 'success' }}
    uses: ./.github/workflows/notify_slack.yml
    with:
      repository_full_name: ${{ inputs.repository_full_name }}
      client_payload_ref: ${{ inputs.client_payload_ref }}
      build_status_message: 'PR Build Failed'
    secrets: inherit
