name: Deploy to dev using serverless
on:
  workflow_call:
    inputs:
      branch:
        description: branch to deploy to dev using serverless
        required: false  
        type: string      

  repository_dispatch:
    types: [deploy-dev]

# Considered secure as they are scoped to the workflow run and are not exposed to the outside world
env:
  REPOSITORY_FULL_NAME: ${{ github.event.repository.full_name }}
  CLIENT_PAYLOAD_REF: ${{ github.event.client_payload.ref }}

jobs:
  notify-slack-build:
    uses: ./.github/workflows/notify_slack.yml
    with:
      repo-full-name: $REPOSITORY_FULL_NAME
      client-payload-ref: $CLIENT_PAYLOAD_REF
      environment: 'dev'
    secrets: inherit

  deploy-to-dev:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          ref: $CLIENT_PAYLOAD_REF

      - name: Set up node.js version
        uses: actions/setup-node@master
        with:
          node-version: 18.x
      - run: npm install -g yarn serverless
      - run: yarn install

      - name: Serverless Authentication
        run: sls config credentials --provider aws --key ${{secrets.AWS_ACCESS_KEY_ID}} --secret ${{secrets.AWS_SECRET_ACCESS_KEY}}

      - name: Deploy to dev
        run: serverless deploy --stage dev

  notify-slack-status-success:
    name: Notify Slack status for successful deployment
    needs: deploy-to-dev
    if: ${{ success() && needs.deploy-to-dev.result == 'success' }}
    uses: ./.github/workflows/notify_slack.yml
    with:
      repo-full-name: $REPOSITORY_FULL_NAME
      client-payload-ref: $CLIENT_PAYLOAD_REF
      build-status-message: 'PR Build Complete'
    secrets: inherit
  
  notify-slack-status-failure:
    name: Notify Slack status for failed deployment
    needs: deploy-to-dev
    if: ${{ failure() || needs.deploy-to-dev.result != 'success' }}
    uses: ./.github/workflows/notify_slack.yml
    with:
      repo-full-name: $REPOSITORY_FULL_NAME
      client-payload-ref: $CLIENT_PAYLOAD_REF
      build-status-message: 'PR Build Failed'
    secrets: inherit
