--- 
name: PR image to ECR
on:
  workflow_call:

jobs:
  call-notify-slack-start:
    uses: ./.github/workflows/notify_slack.yml
    with:
      repository_full_name: ${{ github.event.repository.full_name }}
      client_payload_ref: ${{ github.event.client_payload.ref }} 
      build_status_message: 'success'
      environment: 'dev'
    secrets: inherit
    
  ecr-build-upload:
    name: ECR-build-upload
    runs-on: ubuntu-latest
    needs: call-notify-slack-start

    steps:
      - name: get job url
        uses: Tiryoh/gha-jobid-action@v0
        id: jobs
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          job_name: ECR-build-upload
    
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}
          repository: ${{ github.event.client_payload.repo }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker Layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-${{ github.event.client_payload.repo }}-${{ github.event.client_payload.sha}}
          restore-keys: |
            ${{ runner.os }}-${{ github.event.client_payload.repo }}-


  call-create-sentry:
    uses: ./.github/workflows/create-sentry.yml
    needs: ecr-build-upload
    with:
      sentry_auth_token: ${{ github.event.client_payload.sentry-auth-token }}
      repository_name: ${{ github.event.client_payload.repo-name }}
      sha: ${{ github.event.client_payload.sha }}
    secrets: inherit

  call-notify-slack-end:
    uses: ./.github/workflows/notify_slack.yml
    needs: call-create-sentry
    with:
      repository_full_name: ${{ github.event.repository.full_name }}
      client_payload_ref: ${{ github.event.client_payload.ref }} 
      build_status_message: 'success'
      environment: 'dev'
    secrets: inherit
