# The "Caller" workflow ...
# https://resources.github.com/learn/pathways/automation/intermediate/create-reusable-workflows-in-github-actions/
# https://docs.github.com/en/actions/using-workflows/reusing-workflows
name: CI with reusable and external workflows 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sequential jobs run in parallel
jobs:
  notify-slack:
    uses: ./.github/workflows/notify_slack.yml
    with:
      repository_full_name: 'test'
      client_payload_ref: 'test'    
      build_status_message: 'success'
      environment: 'dev'
    secrets: inherit
    
  create-env-file:
    uses: ./.github/workflows/create-env-file.yml
    with:
      environment: 'dev'
    secrets: inherit

  ecr-upload:
    uses: ./.github/workflows/ecr-upload.yml
    with:
      environment: 'dev'
    secrets: inherit
    
  # Job that calls a reusable workflow with the possibility to pass data
  call-workflow-passing-data:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      node-version: 'v16.14.0'
    # Can enable to set secrets and pass them through environment variables  
    #secrets:
     #envPAT: ${{ secrets.envPAT }}

  # Job that calls a reusable 'external' workflow with the possibility to pass data
  # Commit Sha, Release Tag or Branch Name is required 
  call-external-workflow-passing-data:
    needs: call-workflow-passing-data
    uses: aamirandam/ExternalWorkflow/.github/workflows/external-workflow.yml@v1.2.0
    with:
      node-version: 'v16.14.0'
     
  build:
    needs: [call-workflow-passing-data, call-external-workflow-passing-data]
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Build message
        run: | 
          echo ...
          echo PoC Running build! Post reusable workflows...

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo PoC Build continues...,
          echo PoC Build finishes.
