# The "Caller" workflow ...
# https://resources.github.com/learn/pathways/automation/intermediate/create-reusable-workflows-in-github-actions/
# https://docs.github.com/en/actions/using-workflows/reusing-workflows
name: CI with reusable and external workflows 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sequential jobs run in parallel
jobs:
  notify-slack:
    uses: ./.github/workflows/notify_slack.yml
    with:
      repository_full_name: ${{ github.event.repository.full_name }}
      client_payload_ref: ${{ github.event.client_payload.ref }} 
      build_status_message: 'success'
      environment: 'dev'
    secrets: inherit
    
  create-env-file:
    uses: ./.github/workflows/create-env-file.yml
    with:
      environment: 'dev'
    secrets: inherit

  ecr-upload:
    uses: ./.github/workflows/ecr-upload.yml
    with:
      repository_full_name: ${{ github.event.repository.full_name }}
      actor: ${{ github.actor }}
      sha: ${{ github.sha }}
      environment: 'dev'
    secrets: inherit
  
  call-deploy-serverless:
    uses: ./.github/workflows/deploy-serverless.yml
    with:
      repository_full_name: ${{ github.event.repository.full_name }}  
      client_payload_ref: ${{ github.event.client_payload.ref }} 
      environment: 'dev'
    secrets: inherit
    
  # Job that calls a reusable workflow with the possibility to pass data
  #call-workflow-passing-data:
  #  uses: ./.github/workflows/reusable-workflow.yml
  #  with:
  #    node-version: 'v16.14.0'
    # Can enable to set secrets and pass them through environment variables  
    #secrets:
     #envPAT: ${{ secrets.envPAT }}
    
  # Job that calls a reusable 'external' workflow with the possibility to pass data
  # Commit Sha, Release Tag or Branch Name is required 
  #call-external-workflow-passing-data:
  #  needs: call-workflow-passing-data
  #  uses: aamirandam/ExternalWorkflow/.github/workflows/external-workflow.yml@v1.2.0
  #  with:
  #    node-version: 'v16.14.0'

  call-create-sentry:
    uses: ./.github/workflows/create-sentry.yml
    with:
      environment: 'dev'
      sentry-auth-token: ${{ github.event.client_payload.sentry-auth-token }}
      sentry-org: 'cheddar'
      sentry-project: ${{ github.event.client_payload.repo-name }}
      tag-name: ${{ github.event.client_payload.sha }}
    secrets: inherit
  
  call-ecr-upload-2:
    uses: ./.github/workflows/ecr-upload-2.yml
    secrets: inherit
  
        
     
