name: Notify slack

on:
  workflow_call:
    inputs:
      repository_full_name:
        description: 'Repository full name'
        required: true     
        type: string
      client_payload_ref:
        description: 'Client payload reference'
        required: true
        type: string
      build_status_message:
        description: 'Specifies whether the build failed or passed'
        required: false   
        type: string
      environment: 
        description: 'Environment specific'
        required: true
        type: string

jobs:
  notify-slack:
    name: Notify Slack
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
    - name: Notify slack
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        CORE_BOTS: ${{ secrets.CORE_BOTS }}
      #uses: pullreminders/slack-action@master
      #with:
      #  args: '{\"channel\":\"${{ secrets.CORE_BOTS }}\",\"text\":\"${{ github.event.inputs.build_status_message }} ${{ github.event.inputs.repository_full_name }}/${{  github.event.inputs.client_payload_ref }} container\"}'
      run: |
        echo Secrets: slack bot token: ${{ secrets.SLACK_BOT_TOKEN }}
        echo Secrets: core bots: ${{ secrets.CORE_BOTS }}
        echo inputs: status msg: ${{ inputs.build_status_message }}
        echo inputs: repo full name: ${{ inputs.repository_full_name }}
        echo inputs: client payload ref ${{  inputs.client_payload_ref }}
