name: testing PR Workflow ###

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  tagging:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set private variable
        id: set-tag 
        run: |
          if [ ${{ github.event_name }} == 'pull_request']; then
            echo "tag=pre-release" >> $GITHUB_OUTPUT
          else
            echo "tag=stable" >> $GITHUB_OUTPUT
          fi

      - name: Use private variable
        run: |
          echo "Private variable value: ${{ steps.set-tag.outputs.tag }}"
