name: CI with reusable and external workflows 

on: [push, pull_request]

jobs:
  call-retry-policy:
    name: ECR-build-upload
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      id: checkout
      uses: actions/checkout@v2

    - name: Run command with retries
      id: run_command
      run: |
        retries=3
        count=0
        until [ "$count" -ge "$retries" ]
        do
          if command_to_run; then
            exit 0
          fi
          count=$((count+1))
          echo "Attempt $count failed. Retrying in 5 seconds..."
          sleep 5
        done
        exit 1 # Fail after retries

    - name: Rerun checkout on failure
      if: failure()
      uses: actions/checkout@v2

    - name: Notify failure
      if: failure()
      run: echo "Command failed after retries and checkout rerun."
