# The "Called" workflow, this is being called from a "Caller" workflow
name: CI - Using reusable workflow (in the same repo)
# Changed 'on' to enable this workflow to be called from other workflows
on:
  workflow_call:
    # Introduced 'inputs' to define parameters that can be passed when calling this workflow
    inputs:
      node-version:
        description: "Node version"
        required: true
        type: string

jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Print Build Reusable Workflow Status
        run: echo "Running build on local reusable workflow"
        
      - name: checkout repo
        uses: actions/checkout@v3
      # Modified to use the node-version from the workflow inputs
      - name: use node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}

      - run: npm install
      - run: npm run build

  test: 
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - name: Print Test Reusable Workflow Status
        run: echo "Running tests on local reusable workflow"
        
      - name: checkout repo
        uses: actions/checkout@v3
      # Modified to use the node-version from the workflow inputs
      - name: use node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          
      - run: npm install
      - run: npm run test

  done:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Print Completed Message
        run: echo "Finished running local reusable workflow"
