
name: Deploy to dev using serverless
on:
  workflow_call:
    inputs:
      repository_full_name:
        description: 'Repository full name'
        required: true     
        type: string
      client_payload_ref:
        description: 'Client payload reference'
        required: true
        type: string 
      environment:
        description: 'Environment to run'
        required: true
        type: string

jobs:
  deploy-to-dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    steps:          
      - name: Checkout
        run: echo "test"
